// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesAPIS.Data;

#nullable disable

namespace MoviesAPIS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIMovies.Models.Actor", b =>
                {
                    b.Property<int>("idActor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idActor"));

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idActor");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("APIMovies.Models.Genders", b =>
                {
                    b.Property<int>("idGender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idGender"));

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idGender");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("APIMovies.Models.Movie", b =>
                {
                    b.Property<int>("idMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMovie"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("releaseYear")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMovie");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsidActor")
                        .HasColumnType("int");

                    b.Property<int>("MoviesidMovie")
                        .HasColumnType("int");

                    b.HasKey("ActorsidActor", "MoviesidMovie");

                    b.HasIndex("MoviesidMovie");

                    b.ToTable("MovieActors", (string)null);
                });

            modelBuilder.Entity("GendersMovie", b =>
                {
                    b.Property<int>("GendersidGender")
                        .HasColumnType("int");

                    b.Property<int>("MoviesidMovie")
                        .HasColumnType("int");

                    b.HasKey("GendersidGender", "MoviesidMovie");

                    b.HasIndex("MoviesidMovie");

                    b.ToTable("MovieGenres", (string)null);
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("APIMovies.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsidActor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIMovies.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesidMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GendersMovie", b =>
                {
                    b.HasOne("APIMovies.Models.Genders", null)
                        .WithMany()
                        .HasForeignKey("GendersidGender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIMovies.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesidMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
